//! Token definitions.

use span::Span;

/// One lexed token.
#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    /// The token's kind (and literal payload, if any).
    pub kind: TokenKind,
    /// Where it came from.
    pub span: Span,
    /// Whether a line terminator appeared between the previous token and this
    /// one. Drives semicolon insertion and the no-line-break restrictions
    /// (ECMA-262 3rd ed. §7.9; avmplus `Parser::newline()`,
    /// eval-parse-inlines.h:16).
    pub newline_before: bool,
}

/// What kind of token was lexed.
///
/// Keyword set per avmplus generate-keyword-lexer.as (AS3 mode: both the hard
/// ES3 set and the `!es3_keywords`-gated AS3 additions are reserved).
/// `extends`/`implements` are reserved per the AS3 reference "Reserved words"
/// list (ASC behavior) even though avmplus eval treats them contextually.
/// `each`, `get`, `set` are NOT keywords — they are contextual identifiers
/// (avmplus eval-parse-stmt.cpp:435, eval-parse.cpp:1128).
#[derive(Debug, Clone, PartialEq)]
#[allow(missing_docs)] // variants are the token grammar itself; names + the docs above suffice
pub enum TokenKind {
    // Literals. Integer literals are classified by magnitude into
    // int/uint/Number exactly like avmplus (eval-lex.cpp:1218).
    Int(i32),
    UInt(u32),
    Number(f64),
    Str(String),
    Ident(String),
    /// Regex literal `/pattern/flags` (ECMA-262 3rd ed. §7.8.5); payload
    /// is (pattern source, flags).
    RegExp(String, String),

    // Keywords.
    As,
    Break,
    Case,
    Catch,
    Class,
    Const,
    Continue,
    Default,
    Delete,
    Do,
    Dynamic,
    Else,
    Extends,
    False,
    Final,
    Finally,
    For,
    Function,
    Goto,
    If,
    Implements,
    Import,
    In,
    Include,
    Instanceof,
    Interface,
    Internal,
    Is,
    Namespace,
    Native,
    New,
    Null,
    Override,
    Package,
    Private,
    Protected,
    Public,
    Return,
    Static,
    Super,
    Switch,
    This,
    Throw,
    True,
    Try,
    Typeof,
    Use,
    Var,
    Void,
    While,
    With,

    // Punctuation.
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Semicolon,
    Comma,
    Dot,
    /// `..` — E4X descendant operator; lexed so we can reject it with a good
    /// message rather than mis-lex.
    DotDot,
    /// `...` — rest parameter.
    Ellipsis,
    /// `.<` — type application, a single token (avmplus `T_LeftDotAngle`,
    /// eval-lex.cpp:329). The closing `>` is ordinary `Gt`, split from
    /// `>>`/`>=`/... by the parser (avmplus `rightAngle()`, eval-lex.cpp:164).
    LeftDotAngle,
    Colon,
    ColonColon,
    Question,

    // Operators. Full AS3 compound-assignment set including `&&=`/`||=`
    // (avmplus T_LogicalAndAssign/T_LogicalOrAssign, eval-lex.h:44,46).
    // No `??` — AS3 has none (SPECS §4.6 defers it past P6).
    Assign,
    Eq,
    StrictEq,
    Not,
    Ne,
    StrictNe,
    Plus,
    PlusPlus,
    PlusAssign,
    Minus,
    MinusMinus,
    MinusAssign,
    Star,
    StarAssign,
    Slash,
    SlashAssign,
    Percent,
    PercentAssign,
    Lt,
    Le,
    Shl,
    ShlAssign,
    Gt,
    Ge,
    Shr,
    ShrAssign,
    Ushr,
    UshrAssign,
    BitAnd,
    BitAndAssign,
    LogAnd,
    LogAndAssign,
    BitOr,
    BitOrAssign,
    LogOr,
    LogOrAssign,
    BitXor,
    BitXorAssign,
    BitNot,

    /// End of input. Always the final token of a stream.
    Eof,
}

impl TokenKind {
    /// The keyword for `text`, if it is one.
    pub fn keyword(text: &str) -> Option<TokenKind> {
        use TokenKind::*;
        Some(match text {
            "as" => As,
            "break" => Break,
            "case" => Case,
            "catch" => Catch,
            "class" => Class,
            "const" => Const,
            "continue" => Continue,
            "default" => Default,
            "delete" => Delete,
            "do" => Do,
            "dynamic" => Dynamic,
            "else" => Else,
            "extends" => Extends,
            "false" => False,
            "final" => Final,
            "finally" => Finally,
            "for" => For,
            "function" => Function,
            "goto" => Goto,
            "if" => If,
            "implements" => Implements,
            "import" => Import,
            "in" => In,
            "include" => Include,
            "instanceof" => Instanceof,
            "interface" => Interface,
            "internal" => Internal,
            "is" => Is,
            "namespace" => Namespace,
            "native" => Native,
            "new" => New,
            "null" => Null,
            "override" => Override,
            "package" => Package,
            "private" => Private,
            "protected" => Protected,
            "public" => Public,
            "return" => Return,
            "static" => Static,
            "super" => Super,
            "switch" => Switch,
            "this" => This,
            "throw" => Throw,
            "true" => True,
            "try" => Try,
            "typeof" => Typeof,
            "use" => Use,
            "var" => Var,
            "void" => Void,
            "while" => While,
            "with" => With,
            _ => return None,
        })
    }

    /// A short human-readable name for diagnostics.
    pub fn describe(&self) -> String {
        use TokenKind::*;
        match self {
            Int(_) | UInt(_) | Number(_) => "number literal".to_string(),
            Str(_) => "string literal".to_string(),
            RegExp(..) => "regular expression literal".to_string(),
            Ident(name) => format!("identifier `{name}`"),
            Eof => "end of file".to_string(),
            other => format!("`{}`", other.text()),
        }
    }

    fn text(&self) -> &'static str {
        use TokenKind::*;
        match self {
            RegExp(..) => "/regex/",
            As => "as",
            Break => "break",
            Case => "case",
            Catch => "catch",
            Class => "class",
            Const => "const",
            Continue => "continue",
            Default => "default",
            Delete => "delete",
            Do => "do",
            Dynamic => "dynamic",
            Else => "else",
            Extends => "extends",
            False => "false",
            Final => "final",
            Finally => "finally",
            For => "for",
            Function => "function",
            Goto => "goto",
            If => "if",
            Implements => "implements",
            Import => "import",
            In => "in",
            Include => "include",
            Instanceof => "instanceof",
            Interface => "interface",
            Internal => "internal",
            Is => "is",
            Namespace => "namespace",
            Native => "native",
            New => "new",
            Null => "null",
            Override => "override",
            Package => "package",
            Private => "private",
            Protected => "protected",
            Public => "public",
            Return => "return",
            Static => "static",
            Super => "super",
            Switch => "switch",
            This => "this",
            Throw => "throw",
            True => "true",
            Try => "try",
            Typeof => "typeof",
            Use => "use",
            Var => "var",
            Void => "void",
            While => "while",
            With => "with",
            LParen => "(",
            RParen => ")",
            LBracket => "[",
            RBracket => "]",
            LBrace => "{",
            RBrace => "}",
            Semicolon => ";",
            Comma => ",",
            Dot => ".",
            DotDot => "..",
            Ellipsis => "...",
            LeftDotAngle => ".<",
            Colon => ":",
            ColonColon => "::",
            Question => "?",
            Assign => "=",
            Eq => "==",
            StrictEq => "===",
            Not => "!",
            Ne => "!=",
            StrictNe => "!==",
            Plus => "+",
            PlusPlus => "++",
            PlusAssign => "+=",
            Minus => "-",
            MinusMinus => "--",
            MinusAssign => "-=",
            Star => "*",
            StarAssign => "*=",
            Slash => "/",
            SlashAssign => "/=",
            Percent => "%",
            PercentAssign => "%=",
            Lt => "<",
            Le => "<=",
            Shl => "<<",
            ShlAssign => "<<=",
            Gt => ">",
            Ge => ">=",
            Shr => ">>",
            ShrAssign => ">>=",
            Ushr => ">>>",
            UshrAssign => ">>>=",
            BitAnd => "&",
            BitAndAssign => "&=",
            LogAnd => "&&",
            LogAndAssign => "&&=",
            BitOr => "|",
            BitOrAssign => "|=",
            LogOr => "||",
            LogOrAssign => "||=",
            BitXor => "^",
            BitXorAssign => "^=",
            BitNot => "~",
            Int(_) | UInt(_) | Number(_) | Str(_) | Ident(_) | Eof => unreachable!(),
        }
    }
}
